### ISSUE TITLE
setup UI for testnet

### ISSUE THREAD

**Issue by troggy** [leapdao/bridge-ui#85]
### Delivery

Setup instance of the bridge UI for testnet:
- [x] should be served from `testnet.leapdao.org`
- [ ] should be served from HTTPS. Blocked by https://github.com/leapdao/leap-node/issues/114
- [x] should be configured to testnet leap node (#83)
- [x] should take governance contract address from the network, no hardcode (#84)
- [x] should show network's nodes on the Status page (ideally with #86)
- [x] should have home page with explanation/overview (#59)
- [x] should have social images and description so that link preview looks nice when shared (facebook, twitter, telegram)

### Prerequisites

Requires (to be done separately): #76 

### Bounty setup

Value: 300 DAI

gardener: @troggy / 5%
worker: @troggy / 85%
reviewer: @johannbarbie  / 10%

**Comment by troggy** [comment]
Resolved by:
https://github.com/leapdao/bridge-ui/pull/84
https://github.com/leapdao/bridge-ui/issues/59

**Comment by troggy** [comment]
delivered and payed out
